[package]
name = "s9_parquet"
version = "0.1.0"
edition = "2024"

[dependencies]
parquet = { version = "56.2", features = ["async", "tokio", "arrow"] }
arrow = "56.2"
tokio = { version = "1.48.0", features = ["fs"] }
futures = "0.3"
anyhow = "1.0"
